language: julia

sudo: false

os:
      - linux
      - osx

julia:
      - 1.1
      - nightly

matrix:
      allow_failures:
          - julia: nightly

notifications:
      email: false

after_success:
    - julia -e 'cd(Pkg.dir("NumberIntervals")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
