language: julia

sudo: false

os:
      - linux
      - osx

julia:
      - 1.1
      - nightly

codecov: true

matrix:
      allow_failures:
          - julia: nightly

notifications:
      email: false
